name: ukintensity_console
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
   path: ^1.8.0
   http: ^0.13.5
   intl: ^0.17.0
   ukintensity_integration:
     path: ../ukintensity_integration

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
